disabled_rules:
- trailing_whitespace
- line_length
- function_parameter_count
opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
function_body_length:
    warning: 300
    error: 500
type_body_length:
    warning: 700
    error: 1000
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25

reporter: "xcode"
